
---
- hosts: all
  gather_facts: yes
  become: true

  roles:
    - user
    - dns_setup
    - reflector_rank_mirrors
    - update_upgrade
    - base_pkgs_install
    - user_pkgs_install
    - dotfiles
    - pip
