---
# tasks file for reflector_rank_mirrors
- name: Install reflector
  pacman:
    name: reflector
    state: present

- name: Rank mirrors with reflector
  command: reflector --latest 10 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist
