---
# tasks file for dotfiles
- name: Clone user dotfiles with git
  git: repo={{ dotfiles.url }} dest=/home/{{ user.name }}/{{ dotfiles.destination }} accept_hostkey=yes update=no
  when: dotfiles is defined
  become_user: "{{ user.name }}"

- name: Symlinking the dotfiles with shell script
  command: sh install.sh
  args:
    chdir: /home/{{ user.name }}/{{ dotfiles.destination }}
  become_user: " {{ user.name }}"
